import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js + Tinybird!</a>
        </h1>

        <h3>
          <a href="https://github.com/tinybirdco/web-analytics-starter-kit">
            https://github.com/tinybirdco/web-analytics-starter-kit
          </a>
        </h3>

        <p className={styles.description}>
          Learn more about the Tinybird web Analytics Starter Kit.
          <br />
          <a href="https://github.com/tinybirdco/web-analytics-starter-kit">
            https://github.com/tinybirdco/web-analytics-starter-kit
          </a>
        </p>

        <p className={styles.description}>
          Get started by looking at{" "}
          <code className={styles.code}>pages/api/tracking.ts</code> and{" "}
          <code className={styles.code}>pages/_document.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
